create table public.customers(customer_id varchar(50) Primary key,
customer_zip_code_prefix integer,customer_city	varchar(50),
customer_state	varchar(50));

SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'customer_s'
ORDER BY ordinal_position;

select * from orders_item


create table public.orders(order_id  varchar(50) NOT NULL,
    customer_id  varchar(50),
    order_status  varchar(50),
    order_purchase_timestamp timestamp ,
    order_approved_at timestamp ,
    order_delivered_timestamp timestamp ,
    order_estimated_delivery_date timestamp ,
    invalid_delivery_flag boolean,
    missing_delivery_timestamp boolean );

SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'orders'
ORDER BY ordinal_position;

create table order_item(order_id character varying(50),
    product_id character varying(50),
    seller_id character varying(50),
    price numeric(12,2),
    shipping_charges numeric(12,2)
);

create table payment(order_id character varying(50),
    payment_sequential integer,
    payment_type character varying(50),
    payment_installments integer,
    payment_value numeric);




create table products(product_id character varying(50) NOT NULL,
    product_category_name character varying(100),
    product_weight_g numeric(12,2),
    product_length_cm numeric(12,2),
    product_height_cm numeric(12,2),
    product_width_cm numeric(12,2)
);


--Q1. How many customers are there?
SELECT COUNT(*) AS total_customers
FROM customers;

--Q2. How many orders are there?
SELECT COUNT(*) AS total_orders
FROM orders;

--Q3. How many products are there?
SELECT COUNT(*) AS total_products
FROM products;

--Q4. Display the first 10 customers.
SELECT *
FROM customers
LIMIT 10;

--Q5. What are the unique customer states?
SELECT DISTINCT customer_state
FROM customers
ORDER BY customer_state;

--Q6. What are the unique order statuses?
SELECT DISTINCT order_status
FROM orders;

--Q7. What are the unique payment types?
SELECT DISTINCT payment_type
FROM payments;

--Q8. How many delivered orders are there?
SELECT COUNT(*) AS delivered_orders
FROM orders
WHERE order_status = 'delivered';

--Q9. How many canceled orders are there?
SELECT COUNT(*) AS canceled_orders
FROM orders
WHERE order_status = 'canceled';

--Q10. Which products have price greater than 500?
SELECT *
FROM orders_item
WHERE price > 500
ORDER BY price DESC;

--Q11. What is the total product revenue?
SELECT SUM(price) AS total_revenue
FROM orders_item;

--Q12. What is the total shipping cost?
SELECT SUM(shipping_charges) AS total_shipping
FROM order_items;

--Q13. What is the average product price?
SELECT AVG(price) AS average_price
FROM orders_item;

--Q14. What is the minimum product price?
SELECT MIN(price) AS minimum_price
FROM orders_items;

--Q15. What is the maximum product price?
SELECT MAX(price) AS maximum_price
FROM order_items;

--Q16. How many unique customers placed orders?
SELECT COUNT(DISTINCT customer_id) AS unique_customers
FROM orders;

--Q17. How many unique orders are present in order_items?
SELECT COUNT(DISTINCT order_id) AS unique_orders
FROM orders_item;

--Q18. How many unique products were sold?
SELECT COUNT(DISTINCT product_id) AS products_sold
FROM orders_item;

--Q19. How many unique sellers are there?
SELECT COUNT(DISTINCT seller_id) AS unique_sellers
FROM orders_item;

--Q20. How many different payment types are there?
SELECT COUNT(DISTINCT payment_type) AS payment_types
FROM payments;

--Q21. How many customers are there in each state?
SELECT
    customer_state,
    COUNT(*) AS customer_count
FROM customers
GROUP BY customer_state
ORDER BY customer_count DESC;

--Q22. How many orders are there for each status?
SELECT
    order_status,
    COUNT(*) AS order_count
FROM orders
GROUP BY order_status
ORDER BY order_count DESC;

--Q23. How many payments are made using each payment type?
SELECT
    payment_type,
    COUNT(*) AS payment_count
FROM payments
GROUP BY payment_type
ORDER BY payment_count DESC;

--Q24. What is the total payment value for each payment type?
SELECT
    payment_type,
    SUM(payment_value) AS total_payment
FROM payments
GROUP BY payment_type
ORDER BY total_payment DESC;

--Q25. What is the revenue generated by each product?
SELECT
    product_id,
    SUM(price) AS total_revenue
FROM orders_item
GROUP BY product_id
ORDER BY total_revenue DESC;

--Q26. What is the shipping cost for each product?
SELECT
    product_id,
    SUM(shipping_charges) AS total_shipping
FROM orders_item
GROUP BY product_id
ORDER BY total_shipping DESC;

--Q27. What is the revenue generated by each seller?
SELECT
    seller_id,
    SUM(price) AS total_revenue
FROM orders_item
GROUP BY seller_id
ORDER BY total_revenue DESC;

--Q28. What is the average price for each seller?
SELECT
    seller_id,
    AVG(price) AS average_price
FROM orders_item
GROUP BY seller_id
ORDER BY average_price DESC;

--Q29. How many products has each seller sold?
SELECT
    seller_id,
    COUNT(DISTINCT product_id) AS products_sold
FROM orders_item
GROUP BY seller_id
ORDER BY products_sold DESC;

--Q30. How many orders are there in each state?
SELECT
    c.customer_state,
    COUNT(DISTINCT o.order_id) AS total_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_state
ORDER BY total_orders DESC;

--Q31. Which are the top 10 products by revenue?
SELECT
    product_id,
    SUM(price) AS total_revenue
FROM orders_item
GROUP BY product_id
ORDER BY total_revenue DESC
LIMIT 10;

--Q32. Which are the top 10 sellers by revenue?
SELECT
    seller_id,
    SUM(price) AS total_revenue
FROM orders_item
GROUP BY seller_id
ORDER BY total_revenue DESC
LIMIT 10;

--Q33. What are the 10 most expensive products?
SELECT
    product_id,
    price
FROM orders_item
ORDER BY price DESC
LIMIT 10;

--Q34. What are the 10 cheapest products?
SELECT
    product_id,
    price
FROM orders_item
ORDER BY price
LIMIT 10;

--Q35. Which are the top 10 customers by spending?
SELECT
    o.customer_id,
    SUM(p.payment_value) AS total_spending
FROM orders o
JOIN payments p
    ON o.order_id = p.order_id
GROUP BY o.customer_id
ORDER BY total_spending DESC
LIMIT 10;

--Q36. Which states have the highest number of customers?
SELECT
    customer_state,
    COUNT(*) AS customer_count
FROM customers
GROUP BY customer_state
ORDER BY customer_count DESC;

--Q37. Which payment types have the highest payment value?
SELECT
    payment_type,
    SUM(payment_value) AS total_payment
FROM payment
GROUP BY payment_type
ORDER BY total_payment DESC;

--Q38. What is the revenue from delivered orders?
SELECT
    SUM(oi.price) AS delivered_revenue
FROM orders o
JOIN orders_item oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'delivered';

--Q39. What is the revenue from canceled orders?
SELECT
    SUM(oi.price) AS canceled_revenue
FROM orders o
JOIN orders_item oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'canceled';

--Q40. How many delivered orders are there in each state?
SELECT
    c.customer_state,
    COUNT(DISTINCT o.order_id) AS delivered_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.order_status = 'delivered'
GROUP BY c.customer_state
ORDER BY delivered_orders DESC;

--Q41. What is the revenue of products priced above 500?
SELECT
    SUM(price) AS revenue
FROM orders_item
WHERE price > 500;

--Q42. Which sellers generate revenue from products priced above 1000?
SELECT
    seller_id,
    SUM(price) AS total_revenue
FROM order_items
WHERE price > 1000
GROUP BY seller_id
ORDER BY total_revenue DESC;

--Q43. What is the average seller price for products above 500?
SELECT
    seller_id,
    AVG(price) AS average_price
FROM order_items
WHERE price > 500
GROUP BY seller_id
ORDER BY average_price DESC;

--Q44. Which products generate more than 10,000 revenue?
SELECT
    product_id,
    SUM(price) AS total_revenue
FROM orders_item
GROUP BY product_id
HAVING SUM(price) > 10000
ORDER BY total_revenue DESC;

--Q45. Which sellers generate more than 50,000 revenue?
SELECT
    seller_id,
    SUM(price) AS total_revenue
FROM orders_item
GROUP BY seller_id
HAVING SUM(price) > 50000
ORDER BY total_revenue DESC;

--Q46. Which customers spend more than 5,000?
SELECT
    o.customer_id,
    SUM(p.payment_value) AS total_spending
FROM orders o
JOIN payment p
    ON o.order_id = p.order_id
GROUP BY o.customer_id
HAVING SUM(p.payment_value) > 5000
ORDER BY total_spending DESC;

--Q47. Which states have more than 1,000 customers?
SELECT
    customer_state,
    COUNT(*) AS customer_count
FROM customers
GROUP BY customer_state
HAVING COUNT(*) > 1000
ORDER BY customer_count DESC;

--Q48. Which sellers have sold more than 100 products?
SELECT
    seller_id,
    COUNT(*) AS items_sold
FROM orders_item
GROUP BY seller_id
HAVING COUNT(*) > 100
ORDER BY items_sold DESC;

--Q49. Which payment types have total value above 100,000?
SELECT
    payment_type,
    SUM(payment_value) AS total_payment
FROM payment
GROUP BY payment_type
HAVING SUM(payment_value) > 100000
ORDER BY total_payment DESC;

--Q50. Show customer ID, order ID, product ID and price.
SELECT
    c.customer_id,
    o.order_id,
    oi.product_id,
    oi.price
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN orders_item oi
    ON o.order_id = oi.order_id;
	
--Q51. What is the revenue generated by each customer?
SELECT
    c.customer_id,
    SUM(oi.price) AS total_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN orders_item oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_id
ORDER BY total_revenue DESC;

--Q52. How many orders did each customer place?
SELECT
    c.customer_id,
    COUNT(DISTINCT o.order_id) AS total_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id
ORDER BY total_orders DESC;

--Q53. What products did each customer purchase?
SELECT DISTINCT
    c.customer_id,
    oi.product_id
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN orders_item oi
    ON o.order_id = oi.order_id
ORDER BY c.customer_id;

--Q54. What is the revenue generated by each state?
SELECT
    c.customer_state,
    SUM(oi.price) AS total_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_state
ORDER BY total_revenue DESC;

--Q55. What is the average product price in each state?
SELECT
    c.customer_state,
    AVG(oi.price) AS average_price
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN orders_items oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_state
ORDER BY average_price DESC;
Q56. What are the top 10 customers by revenue?
SELECT
    c.customer_id,
    SUM(oi.price) AS total_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_item oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_id
ORDER BY total_revenue DESC
LIMIT 10;

--Q57. What are the top 10 states by revenue?
SELECT
    c.customer_state,
    SUM(oi.price) AS total_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN orders_item oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_state
ORDER BY total_revenue DESC
LIMIT 10;

--sQ58. What is delivered revenue by state?
SELECT
    c.customer_state,
    SUM(oi.price) AS delivered_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN orders_item oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'delivered'
GROUP BY c.customer_state
ORDER BY delivered_revenue DESC;

--Q59. What is the overall revenue?
SELECT SUM(price) AS total_revenue
FROM order_items;

--Q60. What is the average product price?
SELECT AVG(price) AS average_price
FROM orders_item;

--Q61. Which product generates the highest revenue?
SELECT
    product_id,
    SUM(price) AS total_revenue
FROM orders_item
GROUP BY product_id
ORDER BY total_revenue DESC
LIMIT 1;

--Q62. Which seller generates the highest revenue?
SELECT
    seller_id,
    SUM(price) AS total_revenue
FROM orders_item
GROUP BY seller_id
ORDER BY total_revenue DESC
LIMIT 1;

--Q63. Which customer spends the most?
SELECT
    o.customer_id,
    SUM(p.payment_value) AS total_spending
FROM orders o
JOIN payment p
    ON o.order_id = p.order_id
GROUP BY o.customer_id
ORDER BY total_spending DESC
LIMIT 1;

--Q64. Which state generates the highest revenue?
SELECT
    c.customer_state,
    SUM(oi.price) AS total_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_state
ORDER BY total_revenue DESC
LIMIT 1;

--Q65. Which payment type has the highest total payment value?
SELECT
    payment_type,
    SUM(payment_value) AS total_payment
FROM payment
GROUP BY payment_type
ORDER BY total_payment DESC
LIMIT 1;

--Q66. What percentage of orders are delivered?
SELECT
    ROUND(
        COUNT(*) FILTER (WHERE order_status = 'delivered') * 100.0
        / COUNT(*),
        2
    ) AS delivered_percentage
FROM orders;

--Q67. What percentage of orders are canceled?
SELECT
    ROUND(
        COUNT(*) FILTER (WHERE order_status = 'canceled') * 100.0
        / COUNT(*),
        2
    ) AS canceled_percentage
FROM orders;

--Q68. What is the average customer spending?
SELECT
    AVG(total_spending) AS average_customer_spending
FROM (
    SELECT
        o.customer_id,
        SUM(p.payment_value) AS total_spending
    FROM orders o
    JOIN payment p
        ON o.order_id = p.order_id
    GROUP BY o.customer_id
) ;

--Q69. What is the average revenue per order?
SELECT
    SUM(oi.price) / COUNT(DISTINCT oi.order_id) AS average_order_revenue
FROM orders_item oi;

--Q70. What is the total revenue including shipping?
SELECT
    SUM(price + shipping_charges) AS revenue_including_shipping
FROM orders_item
;

--Q71. Categorize products as High, Medium and Low based on price.
SELECT
    product_id,
    price,
    CASE
        WHEN price >= 1000 THEN 'High'
        WHEN price >= 500 THEN 'Medium'
        ELSE 'Low'
    END AS price_category
FROM orders_item;

--sQ72. How many products are in each price category?
SELECT
    CASE
        WHEN price >= 1000 THEN 'High'
        WHEN price >= 500 THEN 'Medium'
        ELSE 'Low'
    END AS price_category,
    COUNT(*) AS product_count
FROM orders_item
GROUP BY
    CASE
        WHEN price >= 1000 THEN 'High'
        WHEN price >= 500 THEN 'Medium'
        ELSE 'Low'
    END;
	
--Q73. Categorize order statuses.
SELECT
    order_status,
    CASE
        WHEN order_status = 'delivered'
            THEN 'Successful'
        WHEN order_status = 'canceled'
            THEN 'Unsuccessful'
        ELSE 'Other'
    END AS status_category
FROM orders;

--Q74. What is revenue by price category?
SELECT
    CASE
        WHEN price >= 1000 THEN 'High'
        WHEN price >= 500 THEN 'Medium'
        ELSE 'Low'
    END AS price_category,
    SUM(price) AS total_revenue
FROM orders_item
GROUP BY
    CASE
        WHEN price >= 1000 THEN 'High'
        WHEN price >= 500 THEN 'Medium'
        ELSE 'Low'
    END
ORDER BY total_revenue DESC;

--Q75. Classify customers as High Value or Regular.
WITH customer_spending AS (
    SELECT
        o.customer_id,
        SUM(p.payment_value) AS total_spending
    FROM orders o
    JOIN payment p
        ON o.order_id = p.order_id
    GROUP BY o.customer_id
)
SELECT
    customer_id,
    total_spending,
    CASE
        WHEN total_spending > 5000
            THEN 'High Value'
        ELSE 'Regular'
    END AS customer_type
FROM customer_spending
ORDER BY total_spending DESC;

--Q76. Which products have revenue above average product revenue?
SELECT
    product_id,
    SUM(price) AS total_revenue
FROM orders_item
GROUP BY product_id
HAVING SUM(price) > (
    SELECT AVG(product_revenue)
    FROM (
        SELECT
            product_id,
            SUM(price) AS product_revenue
        FROM orders_item
        GROUP BY product_id
    ) x
)
ORDER BY total_revenue DESC;

--Q77. Which sellers generate above-average seller revenue?
WITH seller_revenue AS (
    SELECT
        seller_id,
        SUM(price) AS total_revenue
    FROM orders_item
    GROUP BY seller_id
)
SELECT *
FROM seller_revenue
WHERE total_revenue > (
    SELECT AVG(total_revenue)
    FROM seller_revenue
)
ORDER BY total_revenue DESC;

--Q78. Which customers placed more orders than the average customer?
WITH customer_orders AS (
    SELECT
        customer_id,
        COUNT(DISTINCT order_id) AS total_orders
    FROM orders
    GROUP BY customer_id
)
SELECT *
FROM customer_orders
WHERE total_orders > (
    SELECT AVG(total_orders)
    FROM customer_orders
)
ORDER BY total_orders DESC;

--Q79. Which products were never purchased?
SELECT
    p.product_id,
    p.product_category_name
FROM products p
LEFT JOIN orders_item oi
    ON p.product_id = oi.product_id
WHERE oi.product_id IS NULL;

--Q80. Which customers placed orders but never made a payment?
SELECT DISTINCT
    o.customer_id
FROM orders o
LEFT JOIN payment p
    ON o.order_id = p.order_id
WHERE p.order_id IS NULL;

--Q81. Find the highest-spending customer in each state.
WITH customer_spending AS (
    SELECT
        c.customer_state,
        c.customer_id,
        SUM(p.payment_value) AS total_spending
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN payments p
        ON o.order_id = p.order_id
    GROUP BY
        c.customer_state,
        c.customer_id
)
SELECT *
FROM customer_spending cs
WHERE total_spending = (
    SELECT MAX(total_spending)
    FROM customer_spending
    WHERE customer_state = cs.customer_state
)
ORDER BY customer_state;

--Q82. Find sellers whose revenue is above average seller revenue.
WITH seller_revenue AS (
    SELECT
        seller_id,
        SUM(price) AS total_revenue
    FROM order_items
    GROUP BY seller_id
)
SELECT *
FROM seller_revenue
WHERE total_revenue > (
    SELECT AVG(total_revenue)
    FROM seller_revenue
)
ORDER BY total_revenue DESC;

--Q83. Find the top 3 customers in each state.
WITH customer_spending AS (
    SELECT
        c.customer_state,
        c.customer_id,
        SUM(p.payment_value) AS total_spending,
        RANK() OVER (
            PARTITION BY c.customer_state
            ORDER BY SUM(p.payment_value) DESC
        ) AS rnk
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN payment p
        ON o.order_id = p.order_id
    GROUP BY
        c.customer_state,
        c.customer_id
)
SELECT
    customer_state,
    customer_id,
    total_spending
FROM customer_spending
WHERE rnk <= 3
ORDER BY customer_state, total_spending DESC;


--Window functions calculate across related rows while retaining individual rows, which is why they are useful for rankings, running totals, comparisons, and top-N-per-group analysis.

--Q84. Rank products by revenue.
SELECT
    product_id,
    SUM(price) AS total_revenue,
    RANK() OVER (
        ORDER BY SUM(price) DESC
    ) AS revenue_rank
FROM orders_item
GROUP BY product_id
ORDER BY revenue_rank;

--Q85. Rank sellers by revenue.
SELECT
    seller_id,
    SUM(price) AS total_revenue,
    RANK() OVER (
        ORDER BY SUM(price) DESC
    ) AS revenue_rank
FROM orders_item
GROUP BY seller_id
ORDER BY revenue_rank;

--Q86. Rank states by revenue.
SELECT
    c.customer_state,
    SUM(oi.price) AS total_revenue,
    RANK() OVER (
        ORDER BY SUM(oi.price) DESC
    ) AS state_rank
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN orders_item oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_state
ORDER BY state_rank;

--Q87. Find the top 3 products in each category.
WITH product_revenue AS (
    SELECT
        p.product_category_name,
        oi.product_id,
        SUM(oi.price) AS total_revenue,
        RANK() OVER (
            PARTITION BY p.product_category_name
            ORDER BY SUM(oi.price) DESC
        ) AS rnk
    FROM products p
    JOIN orders_item oi
        ON p.product_id = oi.product_id
    GROUP BY
        p.product_category_name,
        oi.product_id
)
SELECT *
FROM product_revenue
WHERE rnk <= 3
ORDER BY product_category_name, rnk;

--Q88. Find the highest-revenue product in each category.
WITH product_revenue AS (
    SELECT
        p.product_category_name,
        oi.product_id,
        SUM(oi.price) AS total_revenue,
        RANK() OVER (
            PARTITION BY p.product_category_name
            ORDER BY SUM(oi.price) DESC
        ) AS rnk
    FROM products p
    JOIN orders_item oi
        ON p.product_id = oi.product_id
    GROUP BY
        p.product_category_name,
        oi.product_id
)
SELECT *
FROM product_revenue
WHERE rnk = 1;

--Q89. Calculate running revenue by product.
SELECT
    product_id,
    SUM(price) AS product_revenue,
    SUM(SUM(price)) OVER (
        ORDER BY SUM(price) DESC
    ) AS running_revenue
FROM order_items
GROUP BY product_id
ORDER BY product_revenue DESC;

--Q90. Calculate each product's percentage of total revenue.
WITH product_revenue AS (
    SELECT
        product_id,
        SUM(price) AS revenue
    FROM orders_item
    GROUP BY product_id
)
SELECT
    product_id,
    revenue,
    ROUND(
        revenue * 100.0 /
        SUM(revenue) OVER (),
        2
    ) AS revenue_percentage
FROM product_revenue
ORDER BY revenue DESC;

--Q91. Find customers with more than one order.
SELECT
    customer_id,
    COUNT(DISTINCT order_id) AS total_orders
FROM orders
GROUP BY customer_id
HAVING COUNT(DISTINCT order_id) > 1
ORDER BY total_orders DESC;

--Q92. Find customers who placed orders in multiple order statuses.
SELECT
    customer_id,
    COUNT(DISTINCT order_status) AS status_count
FROM orders
GROUP BY customer_id
HAVING COUNT(DISTINCT order_status) > 1
ORDER BY status_count DESC;

--Q93. Find products sold by more than one seller.
SELECT
    product_id,
    COUNT(DISTINCT seller_id) AS seller_count
FROM orders_item
GROUP BY product_id
HAVING COUNT(DISTINCT seller_id) > 1
ORDER BY seller_count DESC;

--Q94. Find the average number of products per order.
SELECT
    AVG(product_count) AS avg_products_per_order
FROM (
    SELECT
        order_id,
        COUNT(*) AS product_count
    FROM orders_item
	
    GROUP BY order_id
) x;

--Q95. Find orders containing more than one product.
SELECT
    order_id,
    COUNT(*) AS product_count
FROM orders_item
GROUP BY order_id
HAVING COUNT(*) > 1
ORDER BY product_count DESC;

--Q96. Find orders where payment value is greater than product value.
WITH order_value AS (
    SELECT
        order_id,
        SUM(price) AS product_value
    FROM orders_item
    GROUP BY order_id
),
payment_value AS (
    SELECT
        order_id,
        SUM(payment_value) AS total_payment
    FROM payment
    GROUP BY order_id
)
SELECT
    ov.order_id,
    ov.product_value,
    pv.total_payment
FROM order_value ov
JOIN payment_value pv
    ON ov.order_id = pv.order_id
WHERE pv.total_payment > ov.product_value
ORDER BY
    pv.total_payment - ov.product_value DESC;
	
--Q97. Find customers who have both delivered and canceled orders.
SELECT
    customer_id
FROM orders
GROUP BY customer_id
HAVING
    COUNT(*) FILTER (WHERE order_status = 'delivered') > 0
    AND
    COUNT(*) FILTER (WHERE order_status = 'canceled') > 0;

--Q98. Find the state with the highest number of customers and compare it with the state with the highest revenue.
WITH customer_state AS (
    SELECT
        customer_state,
        COUNT(*) AS customers
    FROM customers
    GROUP BY customer_state
),
revenue_state AS (
    SELECT
        c.customer_state,
        SUM(oi.price) AS revenue
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN orders_item oi
        ON o.order_id = oi.order_id
    GROUP BY c.customer_state
)
SELECT
    cs.customer_state,
    cs.customers,
    rs.revenue
FROM customer_state cs
JOIN revenue_state rs
    ON cs.customer_state = rs.customer_state
ORDER BY cs.customers DESC;

--Q99. Which state generates the highest shipping cost?
SELECT
    c.customer_state,
    SUM(oi.shipping_charges) AS total_shipping
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN orders_item oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_state
ORDER BY total_shipping DESC
LIMIT 1;

--Q100. Which payment type is used most frequently?
SELECT
    payment_type,
    COUNT(*) AS transaction_count
FROM payment
GROUP BY payment_type
ORDER BY transaction_count DESC
LIMIT 1;




--Q Which delivered orders have a payment amount 
--lower than the total product price plus shipping charges,
--and what are their payment type and installment details?

WITH order_items_total AS (
    SELECT
        order_id,
        SUM(price) AS product_revenue,
        SUM(shipping_charges) AS shipping_charges
        
    FROM orders_item
    GROUP BY order_id
),

payments_total AS (
    SELECT
        order_id,
        SUM(payment_value) AS total_payment,
        MAX(payment_installments) AS installments,
        STRING_AGG(DISTINCT payment_type, ', ') AS payment_type
    FROM payment
    GROUP BY order_id
)

SELECT
    o.order_id,
    o.order_status AS delivery_status,

    oi.product_revenue,
    oi.shipping_charges,
    

    oi.product_revenue
        + oi.shipping_charges
        - oi.total_discount AS expected_amount,

    COALESCE(p.total_payment, 0) AS total_payment,

    COALESCE(p.payment_type, 'No Payment') AS payment_type,
    COALESCE(p.installments, 0) AS installments,

    (
        oi.product_revenue
        + oi.shipping_charges
        - oi.total_discount
        - COALESCE(p.total_payment, 0)
    ) AS unpaid_amount

FROM orders o

JOIN order_items_total oi
    ON o.order_id = oi.order_id

LEFT JOIN payments_total p
    ON o.order_id = p.order_id

WHERE o.order_status = 'delivered'

ORDER BY unpaid_amount DESC;






--Q what was the unpaid amount of delivered orders?
WITH order_items_total AS (
    SELECT
        order_id,
        SUM(price) AS product_revenue,
        SUM(shipping_charges) AS shipping_charges
    FROM orders_item
    GROUP BY order_id
),

payments_total AS (
    SELECT
        order_id,
        SUM(payment_value) AS total_payment,
        MAX(payment_installments) AS installments,
        STRING_AGG(DISTINCT payment_type, ', ') AS payment_type
    FROM payment
    GROUP BY order_id
)

SELECT
    o.order_id,

    -- Delivery status
    o.order_status AS delivery_status,

    -- Product and shipping
    oi.product_revenue,
    oi.shipping_charges,

    -- Expected amount
    oi.product_revenue + oi.shipping_charges AS expected_amount,

    -- Actual payment
    COALESCE(p.total_payment, 0) AS total_payment,

    -- Payment details
    COALESCE(p.payment_type, 'No Payment') AS payment_type,
    COALESCE(p.installments, 0) AS installments,

    -- Difference
    (
        oi.product_revenue
        + oi.shipping_charges
        - COALESCE(p.total_payment, 0)
    ) AS unpaid_amount

FROM orders o

JOIN order_items_total oi
    ON o.order_id = oi.order_id

LEFT JOIN payments_total p
    ON o.order_id = p.order_id

WHERE o.order_status = 'delivered'

ORDER BY unpaid_amount DESC;


--Q total unpaid amount for all delivered orders

WITH order_items_total AS (
    SELECT
        order_id,
        SUM(price) AS product_revenue,
        SUM(shipping_charges) AS shipping_charges
    FROM orders_item
    GROUP BY order_id
),

payments_total AS (
    SELECT
        order_id,
        SUM(payment_value) AS total_payment
    FROM payment
    GROUP BY order_id
)

SELECT
    SUM(
        oi.product_revenue
        + oi.shipping_charges
        - COALESCE(p.total_payment, 0)
    ) AS total_unpaid_amount
FROM orders o
JOIN order_items_total oi
    ON o.order_id = oi.order_id
LEFT JOIN payments_total p
    ON o.order_id = p.order_id
WHERE o.order_status = 'delivered'
AND COALESCE(p.total_payment, 0)
    < oi.product_revenue + oi.shipping_charges;


select SUM(payment_value) from payment

SELECT
    SUM(p.payment_value) AS total_paid_amount
FROM payment p
JOIN orders o
    ON p.order_id = o.order_id
WHERE o.order_status = 'delivered';



--Q What is the total revenue, expected payment, actual paid amount, and unpaid amount for delivered orders?
WITH order_items_total AS (
    SELECT
        order_id,
        SUM(price) AS total_revenue,
        SUM(shipping_charges) AS total_shipping
    FROM orders_item
    GROUP BY order_id
),

payments_total AS (
    SELECT
        order_id,
        SUM(payment_value) AS total_paid
    FROM payment
    GROUP BY order_id
)

SELECT
    SUM(oi.total_revenue) AS total_revenue,

    SUM(oi.total_shipping) AS total_shipping,

    SUM(
        oi.total_revenue + oi.total_shipping
    ) AS total_payment,

    SUM(
        COALESCE(p.total_paid, 0)
    ) AS total_paid,

    SUM(
        (oi.total_revenue + oi.total_shipping)
        - COALESCE(p.total_paid, 0)
    ) AS total_unpaid

FROM orders o

JOIN order_items_total oi
    ON o.order_id = oi.order_id

LEFT JOIN payments_total p
    ON o.order_id = p.order_id

WHERE o.order_status = 'delivered';



--Q How many delivered orders have an unpaid amount?
WITH order_items_total AS (
    SELECT
        order_id,
        SUM(price + shipping_charges) AS expected_amount
    FROM orders_item
    GROUP BY order_id
),

payments_total AS (
    SELECT
        order_id,
        SUM(payment_value) AS total_paid
    FROM payment
    GROUP BY order_id
)

SELECT
    COUNT(*) AS unpaid_delivered_orders
FROM orders o
JOIN order_items_total oi
    ON o.order_id = oi.order_id
LEFT JOIN payments_total p
    ON o.order_id = p.order_id
WHERE o.order_status = 'delivered'
AND COALESCE(p.total_paid, 0) < oi.expected_amount;

--Q How many delivered orders have an unpaid amount, broken down by year?
WITH order_items_total AS (
    SELECT
        order_id,
        SUM(price + shipping_charges) AS expected_amount
    FROM orders_item
    GROUP BY order_id
),

payments_total AS (
    SELECT
        order_id,
        SUM(payment_value) AS total_paid
    FROM payment
    GROUP BY order_id
)

SELECT
    EXTRACT(YEAR FROM o.order_purchase_timestamp) AS year,

    COUNT(*) AS unpaid_delivered_orders

FROM orders o

JOIN order_items_total oi
    ON o.order_id = oi.order_id

LEFT JOIN payments_total p
    ON o.order_id = p.order_id

WHERE o.order_status = 'delivered'
AND COALESCE(p.total_paid, 0) < oi.expected_amount

GROUP BY
    EXTRACT(YEAR FROM o.order_purchase_timestamp)

ORDER BY year;



CREATE VIEW OrderPaymentAnalysis AS

WITH order_items_total AS (
    SELECT
        order_id,
        SUM(price) AS product_revenue,
        SUM(shipping_charges) AS shipping_charges
    FROM orders_item
    GROUP BY order_id
),

payments_total AS (
    SELECT
        order_id,
        SUM(payment_value) AS total_paid,
        STRING_AGG(DISTINCT payment_type, ', ') AS payment_type,
        MAX(payment_installments) AS installments
    FROM payment
    GROUP BY order_id
)

SELECT
    o.order_id,
    EXTRACT(YEAR FROM o.order_purchase_timestamp) AS order_year,
    o.order_status,

    oi.product_revenue,
    oi.shipping_charges,

    oi.product_revenue + oi.shipping_charges
        AS expected_payment,

    COALESCE(p.total_paid, 0)
        AS total_paid,

    (
        oi.product_revenue
        + oi.shipping_charges
        - COALESCE(p.total_paid, 0)
    ) AS unpaid_amount,

    COALESCE(p.payment_type, 'No Payment')
        AS payment_type,

    COALESCE(p.installments, 0)
        AS installments

FROM orders o

JOIN order_items_total oi
    ON o.order_id = oi.order_id

LEFT JOIN payments_total p
    ON o.order_id = p.order_id;

SELECT *
FROM OrderPaymentAnalysis
LIMIT 10;

select 1

SELECT *
FROM OrderPaymentAnalysis
LIMIT 10;
